services:
  sybil:
    image: manifoldlabs/sybil-api:latest
    healthcheck: 
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost/ping"]
      interval: "1s"
    env_file: .env
    depends_on:
      searxng:
        condition: service_healthy
    build:
      context: ./api
      platforms: 
      - linux/arm64
    environment:
      - DEBUG=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`localhost`)
      - traefik.http.routers.api.tls=false
      - traefik.http.routers.api.tls.certresolver=
      - traefik.http.services.api.loadbalancer.server.port=80
  traefik:
    image: traefik:v2.3
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/traefik/traefik.dev.toml:/etc/traefik/traefik.toml

  searxng:
    image: docker.io/searxng/searxng:latest
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8080 || exit 1
      interval: 2s
    restart: always
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    ports:
      - 8080:8080

volumes:
  searx-data:
