services:
  api:
    image: manifoldlabs/sybil-api:latest
    build:
      platforms: 
      - linux/amd64
      context: ./api

  miner-cache:
    image: manifoldlabs/sybil-miner-cache:latest
    build:
      platforms: 
      - linux/amd64
      context: ./miner-cache
