name: Push Images

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "sybil/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push sybil api
        uses: docker/build-push-action@v6
        with:
          context: sybil
          push: true
          tags: |
            manifoldlabs/sybil-api:latest
            manifoldlabs/sybil-api:${{ steps.vars.outputs.sha_short }}
